-- Update the trigger function to insert the new 'Anamnese Bio - Padrão'
CREATE OR REPLACE FUNCTION public.handle_new_profissional_template()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.anamnese_templates (profissional_id, nome_template, eh_padrao, perguntas)
  VALUES (
    NEW.id,
    'Anamnese Bio - Padrão',
    true,
    '[
      {"id": "sec_1", "tipo": "section", "titulo": "I. DADOS PESSOAIS E ANTROPOMÉTRICOS"},
      {"id": "dp_nome", "tipo": "text", "titulo": "Nome Completo", "obrigatoria": true},
      {"id": "dp_nasc", "tipo": "date", "titulo": "Data de Nascimento"},
      {"id": "dp_idade", "tipo": "number", "titulo": "Idade"},
      {"id": "dp_sexo", "tipo": "radio", "titulo": "Sexo", "opcoes": ["Feminino", "Masculino"]},
      {"id": "dp_prof", "tipo": "text", "titulo": "Profissão"},
      {"id": "dp_email", "tipo": "email", "titulo": "E-mail"},
      {"id": "dp_tel", "tipo": "tel", "titulo": "Telefone"},
      {"id": "dp_alt", "tipo": "number", "titulo": "Altura (cm)"},
      {"id": "dp_peso", "tipo": "number", "titulo": "Peso (kg)"},
      {"id": "dp_imc", "tipo": "number", "titulo": "IMC (Calculado via sistema/manual)"},
      {"id": "dp_cint", "tipo": "number", "titulo": "Circunferência da Cintura (cm)"},
      {"id": "dp_quad", "tipo": "number", "titulo": "Circunferência do Quadril (cm)"},
      {"id": "dp_rcq", "tipo": "number", "titulo": "Razão Cintura/Quadril (Calculado)"},
      {"id": "sec_2", "tipo": "section", "titulo": "II. QUEIXA PRINCIPAL E EXPECTATIVAS"},
      {"id": "qp_motivo", "tipo": "textarea", "titulo": "Qual o principal motivo da sua consulta hoje?"},
      {"id": "qp_obj", "tipo": "textarea", "titulo": "Quais são seus objetivos com este tratamento?"},
      {"id": "sec_3", "tipo": "section", "titulo": "III. HISTÓRICO DE SAÚDE E FAMILIAR"},
      {"id": "hs_doencas", "tipo": "checkbox", "titulo": "Doenças diagnosticadas", "opcoes": ["Hipertensão Arterial", "Diabetes Mellitus", "Dislipidemias", "Doenças Cardíacas", "Doenças Tireoidianas", "Doenças Renais", "Doenças Hepáticas", "Doenças Gastrointestinais", "Alergias ou Intolerâncias", "Doenças Autoimunes", "Osteoporose/Osteopenia/Artrose", "Fibromialgia", "Depressão/Ansiedade/Síndrome do Pânico", "Câncer", "Outras"]},
      {"id": "hs_doencas_espec", "tipo": "text", "titulo": "Especifique as Doenças Cardíacas/Autoimunes/Câncer/Outras (se aplicável)"},
      {"id": "hs_meds", "tipo": "textarea", "titulo": "Medicamentos em uso (com dosagem)"},
      {"id": "hs_supl", "tipo": "textarea", "titulo": "Suplementos em uso (com dosagem)"},
      {"id": "hs_cirurg", "tipo": "textarea", "titulo": "Cirurgias ou Internações relevantes"},
      {"id": "hs_alergias", "tipo": "checkbox", "titulo": "Alergias/Sensibilidades", "opcoes": ["Medicamentos", "Alimentos", "Pólen/Poeira/Fumaça/Ácaros", "Metais/Cosméticos/Tinturas de cabelo", "Outras"]},
      {"id": "hs_alergias_espec", "tipo": "text", "titulo": "Especifique Medicamentos/Alimentos/Outras alergias"},
      {"id": "hs_fam", "tipo": "checkbox", "titulo": "Histórico Familiar", "opcoes": ["Hipertensão", "Diabetes", "Câncer", "Doença Cardíaca", "Doença Tireoidiana", "Doença Autoimune", "Osteoporose", "Outros"]},
      {"id": "hs_fam_espec", "tipo": "text", "titulo": "Especifique outros familiares"},
      {"id": "sec_4", "tipo": "section", "titulo": "IV. AVALIAÇÃO POR SISTEMAS (Sintomas Atuais)"},
      {"id": "av_cardio", "tipo": "checkbox", "titulo": "1. Cardiovascular e Circulatório", "opcoes": ["Dor no peito", "Palpitações", "Mãos/pés frios", "Inchaço (pernas, mãos)", "Pressão alta", "Tonturas", "Formigamento nos membros", "Varizes", "Outros"]},
      {"id": "av_cardio_desc", "tipo": "textarea", "titulo": "Descrição (Cardiovascular)"},
      {"id": "av_gastro", "tipo": "checkbox", "titulo": "2. Gastrointestinal e Digestório", "opcoes": ["Refluxo/azia", "Má digestão", "Gases/flatulência", "Inchaço abdominal", "Diarreia frequente", "Constipação", "Fezes irregulares", "Dor abdominal", "Sensibilidade a alimentos específicos", "Mau hálito", "Outros"]},
      {"id": "av_gastro_freq", "tipo": "number", "titulo": "Frequência de evacuações (número/semana)"},
      {"id": "av_gastro_bristol", "tipo": "text", "titulo": "Consistência (Escala de Bristol)"},
      {"id": "av_hep", "tipo": "checkbox", "titulo": "3. Função Hepática e Biliar", "opcoes": ["Fadiga excessiva", "Dificuldade para digerir gorduras", "Dor no lado direito do abdômen", "Icterícia", "Urina escura", "Fezes claras", "Outros"]},
      {"id": "av_panc", "tipo": "checkbox", "titulo": "4. Função Pancreática e Metabolismo do Açúcar", "opcoes": ["Sede excessiva", "Fome frequente", "Urinar muito", "Sonolência após refeições", "Histórico de diabetes na família", "Outros"]},
      {"id": "av_renal", "tipo": "checkbox", "titulo": "5. Função Renal e Urinária", "opcoes": ["Dor ao urinar", "Urinar frequentemente", "Urina escura/com cheiro forte", "Inchaço facial ou corporal", "Infecções urinárias de repetição", "Outros"]},
      {"id": "av_pulm", "tipo": "checkbox", "titulo": "6. Função Pulmonar e Respiratória", "opcoes": ["Tosse crônica", "Falta de ar", "Chiado no peito", "Asma/Bronquite", "Resfriados frequentes", "Outros"]},
      {"id": "av_nerv", "tipo": "checkbox", "titulo": "7. Sistema Nervoso e Cognitivo", "opcoes": ["Estresse elevado", "Ansiedade", "Depressão", "Irritabilidade", "Mudanças de humor", "Dificuldade de concentração", "Perda de memória", "Dores de cabeça frequentes", "Tontura", "Dormência/formigamento", "Outros"]},
      {"id": "av_oss", "tipo": "checkbox", "titulo": "8. Saúde Óssea e Articular", "opcoes": ["Dores nas articulações", "Rigidez matinal", "Dores musculares", "Fraturas frequentes", "Osteoporose/osteopenia", "Artrose/artrite/reumatismo", "Outros"]},
      {"id": "av_end_tir", "tipo": "checkbox", "titulo": "9A. Sistema Endócrino e Hormonal - Tireoide", "opcoes": ["Cansaço/fadiga", "Ganho de peso", "Dificuldade para perder peso", "Perda de cabelo", "Pele seca", "Intolerância ao frio", "Irregularidade menstrual", "Constipação", "Dificuldade de concentração", "Outros"]},
      {"id": "av_end_mul", "tipo": "checkbox", "titulo": "9B. Sistema Endócrino e Hormonal - Para Mulheres", "opcoes": ["Ciclo menstrual irregular", "TPM intensa", "Menopausa/Climatério", "Problemas ginecológicos", "Alterações nas mamas", "Outros"]},
      {"id": "av_end_mul_espec", "tipo": "text", "titulo": "Especifique os sintomas de Menopausa ou Problemas ginecológicos"},
      {"id": "av_end_hom", "tipo": "checkbox", "titulo": "9C. Sistema Endócrino e Hormonal - Para Homens", "opcoes": ["Baixa libido", "Disfunção erétil", "Alterações na próstata", "Fadiga", "Outros"]},
      {"id": "av_imune", "tipo": "checkbox", "titulo": "10. Sistema Imunológico", "opcoes": ["Resfriados/gripes frequentes", "Infecções de repetição", "Cicatrização lenta", "Herpes de repetição", "Candidíase de repetição", "Outros"]},
      {"id": "sec_5", "tipo": "section", "titulo": "V. ESTILO DE VIDA E HÁBITOS"},
      {"id": "ev_alim_desc", "tipo": "textarea", "titulo": "1. Alimentação - Descrição da alimentação diária"},
      {"id": "ev_alim_ultra", "tipo": "number", "titulo": "Frequência de ultraprocessados (número/semana)"},
      {"id": "ev_alim_acuc", "tipo": "number", "titulo": "Frequência de açúcares (número/semana)"},
      {"id": "ev_alim_farin", "tipo": "number", "titulo": "Frequência de farináceos refinados (número/semana)"},
      {"id": "ev_alim_frit", "tipo": "number", "titulo": "Frequência de frituras (número/semana)"},
      {"id": "ev_alim_carne", "tipo": "number", "titulo": "Frequência de carnes vermelhas (número/semana)"},
      {"id": "ev_alim_peixe", "tipo": "number", "titulo": "Frequência de peixes (número/semana)"},
      {"id": "ev_alim_fruta", "tipo": "number", "titulo": "Porções de frutas (número/dia)"},
      {"id": "ev_alim_veg", "tipo": "number", "titulo": "Porções de vegetais (número/dia)"},
      {"id": "ev_alim_lat", "tipo": "text", "titulo": "Consumo de laticínios (Sim/Não e Frequência)", "placeholder": "Ex: Sim, 2x ao dia"},
      {"id": "ev_alim_glu", "tipo": "text", "titulo": "Consumo de glúten (Sim/Não e Frequência)", "placeholder": "Ex: Sim, 3x na semana"},
      {"id": "ev_alim_rest", "tipo": "textarea", "titulo": "Restrições alimentares"},
      {"id": "ev_hidr_agua", "tipo": "number", "titulo": "2. Hidratação - Consumo de água por dia (litros)"},
      {"id": "ev_hidr_beb", "tipo": "checkbox", "titulo": "Outras bebidas", "opcoes": ["Bebidas açucaradas", "Chá"]},
      {"id": "ev_hidr_cafe", "tipo": "number", "titulo": "Café (xícaras/dia)"},
      {"id": "ev_hidr_outros", "tipo": "textarea", "titulo": "Outras bebidas (especifique)"},
      {"id": "ev_sono_horas", "tipo": "number", "titulo": "3. Sono - Horas de sono por noite"},
      {"id": "ev_sono_prob", "tipo": "checkbox", "titulo": "Problemas de sono", "opcoes": ["Dificuldade para iniciar o sono", "Acorda muitas vezes à noite", "Sono não reparador", "Insônia", "Ronco/Apneia"]},
      {"id": "ev_sono_outros", "tipo": "textarea", "titulo": "Outros problemas de sono"},
      {"id": "ev_estresse_nivel", "tipo": "number", "titulo": "4. Estresse e Saúde Mental - Nível de estresse (0-10)"},
      {"id": "ev_estresse_fontes", "tipo": "checkbox", "titulo": "Fontes de estresse", "opcoes": ["Trabalho", "Família", "Finanças", "Saúde", "Outros"]},
      {"id": "ev_estresse_sintomas", "tipo": "checkbox", "titulo": "Sintomas emocionais", "opcoes": ["Ansiedade", "Tristeza persistente", "Irritabilidade", "Crises de pânico"]},
      {"id": "ev_estresse_hobbies", "tipo": "textarea", "titulo": "Hobbies/atividades relaxantes"},
      {"id": "ev_fis_pratica", "tipo": "radio", "titulo": "5. Atividade Física - Pratica?", "opcoes": ["Sim", "Não"]},
      {"id": "ev_fis_tipo", "tipo": "text", "titulo": "Tipo"},
      {"id": "ev_fis_freq", "tipo": "number", "titulo": "Frequência (número/semana)"},
      {"id": "ev_fis_dur", "tipo": "number", "titulo": "Duração (minutos)"},
      {"id": "ev_tox_fumo", "tipo": "text", "titulo": "6. Exposição a Toxinas - Tabagismo", "placeholder": "Sim/Não/Ex-fumante (tempo)"},
      {"id": "ev_tox_cigarros", "tipo": "number", "titulo": "Cigarros por dia (se sim)"},
      {"id": "ev_tox_alcool", "tipo": "text", "titulo": "Consumo de álcool (Sim/Não + freq/qtd)"},
      {"id": "ev_tox_quimicos", "tipo": "textarea", "titulo": "Exposição a químicos no trabalho/casa"},
      {"id": "ev_tox_poluicao", "tipo": "textarea", "titulo": "Moradia próxima a áreas de poluição"},
      {"id": "ev_tox_cosmeticos", "tipo": "radio", "titulo": "Utiliza cosméticos/produtos com muitos químicos?", "opcoes": ["Sim", "Não"]},
      {"id": "ev_tox_panelas", "tipo": "radio", "titulo": "Utiliza panelas de alumínio?", "opcoes": ["Sim", "Não"]},
      {"id": "sec_6", "tipo": "section", "titulo": "VI. QUEIXAS ESTÉTICAS ESPECÍFICAS"},
      {"id": "qe_pele", "tipo": "checkbox", "titulo": "1. Pele", "opcoes": ["Acne", "Oleosidade excessiva", "Ressecamento", "Manchas", "Flacidez", "Rugas/Linhas de expressão", "Sensibilidade/Vermelhidão", "Rosácea", "Dermatite", "Coceira"]},
      {"id": "qe_pele_acne_loc", "tipo": "text", "titulo": "Localização da Acne"},
      {"id": "qe_pele_tipo", "tipo": "radio", "titulo": "Tipo de pele", "opcoes": ["Seca", "Normal", "Mista", "Oleosa", "Sensível"]},
      {"id": "qe_pele_rotina", "tipo": "textarea", "titulo": "Rotina de cuidados com a pele"},
      {"id": "qe_pele_produtos", "tipo": "textarea", "titulo": "Produtos utilizados"},
      {"id": "qe_cabelo", "tipo": "checkbox", "titulo": "2. Cabelo", "opcoes": ["Queda de cabelo", "Oleosidade excessiva", "Ressecamento/Quebra", "Fios finos/Frágeis", "Caspa/Dermatite no couro cabeludo"]},
      {"id": "qe_cabelo_outros", "tipo": "textarea", "titulo": "Outros (Cabelo)"},
      {"id": "qe_unhas", "tipo": "checkbox", "titulo": "3. Unhas", "opcoes": ["Frágeis/Quebradiças", "Manchas", "Fungos", "Crescimento lento"]},
      {"id": "qe_unhas_outros", "tipo": "textarea", "titulo": "Outros (Unhas)"},
      {"id": "qe_corp", "tipo": "checkbox", "titulo": "4. Corporal", "opcoes": ["Gordura localizada", "Celulite", "Flacidez corporal", "Inchaço"]},
      {"id": "qe_corp_loc", "tipo": "text", "titulo": "Localização (Gordura/Flacidez/Inchaço) e Grau (Celulite)"},
      {"id": "qe_corp_outros", "tipo": "textarea", "titulo": "Outros (Corporal)"},
      {"id": "qe_olhos", "tipo": "checkbox", "titulo": "5. Olhos", "opcoes": ["Olheiras", "Bolsas sob os olhos", "Rugas ao redor dos olhos", "Ressecamento ocular", "Fadiga visual", "Visão embaçada"]},
      {"id": "qe_olhos_outros", "tipo": "textarea", "titulo": "Outros (Olhos)"},
      {"id": "sec_7", "tipo": "section", "titulo": "VII. OBSERVAÇÕES DO PROFISSIONAL"},
      {"id": "obs_prof", "tipo": "textarea", "titulo": "Anotações para o profissional"},
      {"id": "obs_ass_cli", "tipo": "text", "titulo": "Assinatura do Cliente"},
      {"id": "obs_ass_prof", "tipo": "text", "titulo": "Assinatura do Profissional"},
      {"id": "amputados", "tipo": "radio", "titulo": "Tem órgãos amputados? (Biorressonância não identifica órgãos ausentes)", "opcoes": ["Sim", "Não"], "obrigatoria": true}
    ]'::jsonb
  );
  RETURN NEW;
END;
$function$;

-- Update existing templates that were named "Padrão Morgana" to the new template
UPDATE public.anamnese_templates
SET 
  nome_template = 'Anamnese Bio - Padrão',
  perguntas = '[
      {"id": "sec_1", "tipo": "section", "titulo": "I. DADOS PESSOAIS E ANTROPOMÉTRICOS"},
      {"id": "dp_nome", "tipo": "text", "titulo": "Nome Completo", "obrigatoria": true},
      {"id": "dp_nasc", "tipo": "date", "titulo": "Data de Nascimento"},
      {"id": "dp_idade", "tipo": "number", "titulo": "Idade"},
      {"id": "dp_sexo", "tipo": "radio", "titulo": "Sexo", "opcoes": ["Feminino", "Masculino"]},
      {"id": "dp_prof", "tipo": "text", "titulo": "Profissão"},
      {"id": "dp_email", "tipo": "email", "titulo": "E-mail"},
      {"id": "dp_tel", "tipo": "tel", "titulo": "Telefone"},
      {"id": "dp_alt", "tipo": "number", "titulo": "Altura (cm)"},
      {"id": "dp_peso", "tipo": "number", "titulo": "Peso (kg)"},
      {"id": "dp_imc", "tipo": "number", "titulo": "IMC (Calculado via sistema/manual)"},
      {"id": "dp_cint", "tipo": "number", "titulo": "Circunferência da Cintura (cm)"},
      {"id": "dp_quad", "tipo": "number", "titulo": "Circunferência do Quadril (cm)"},
      {"id": "dp_rcq", "tipo": "number", "titulo": "Razão Cintura/Quadril (Calculado)"},
      {"id": "sec_2", "tipo": "section", "titulo": "II. QUEIXA PRINCIPAL E EXPECTATIVAS"},
      {"id": "qp_motivo", "tipo": "textarea", "titulo": "Qual o principal motivo da sua consulta hoje?"},
      {"id": "qp_obj", "tipo": "textarea", "titulo": "Quais são seus objetivos com este tratamento?"},
      {"id": "sec_3", "tipo": "section", "titulo": "III. HISTÓRICO DE SAÚDE E FAMILIAR"},
      {"id": "hs_doencas", "tipo": "checkbox", "titulo": "Doenças diagnosticadas", "opcoes": ["Hipertensão Arterial", "Diabetes Mellitus", "Dislipidemias", "Doenças Cardíacas", "Doenças Tireoidianas", "Doenças Renais", "Doenças Hepáticas", "Doenças Gastrointestinais", "Alergias ou Intolerâncias", "Doenças Autoimunes", "Osteoporose/Osteopenia/Artrose", "Fibromialgia", "Depressão/Ansiedade/Síndrome do Pânico", "Câncer", "Outras"]},
      {"id": "hs_doencas_espec", "tipo": "text", "titulo": "Especifique as Doenças Cardíacas/Autoimunes/Câncer/Outras (se aplicável)"},
      {"id": "hs_meds", "tipo": "textarea", "titulo": "Medicamentos em uso (com dosagem)"},
      {"id": "hs_supl", "tipo": "textarea", "titulo": "Suplementos em uso (com dosagem)"},
      {"id": "hs_cirurg", "tipo": "textarea", "titulo": "Cirurgias ou Internações relevantes"},
      {"id": "hs_alergias", "tipo": "checkbox", "titulo": "Alergias/Sensibilidades", "opcoes": ["Medicamentos", "Alimentos", "Pólen/Poeira/Fumaça/Ácaros", "Metais/Cosméticos/Tinturas de cabelo", "Outras"]},
      {"id": "hs_alergias_espec", "tipo": "text", "titulo": "Especifique Medicamentos/Alimentos/Outras alergias"},
      {"id": "hs_fam", "tipo": "checkbox", "titulo": "Histórico Familiar", "opcoes": ["Hipertensão", "Diabetes", "Câncer", "Doença Cardíaca", "Doença Tireoidiana", "Doença Autoimune", "Osteoporose", "Outros"]},
      {"id": "hs_fam_espec", "tipo": "text", "titulo": "Especifique outros familiares"},
      {"id": "sec_4", "tipo": "section", "titulo": "IV. AVALIAÇÃO POR SISTEMAS (Sintomas Atuais)"},
      {"id": "av_cardio", "tipo": "checkbox", "titulo": "1. Cardiovascular e Circulatório", "opcoes": ["Dor no peito", "Palpitações", "Mãos/pés frios", "Inchaço (pernas, mãos)", "Pressão alta", "Tonturas", "Formigamento nos membros", "Varizes", "Outros"]},
      {"id": "av_cardio_desc", "tipo": "textarea", "titulo": "Descrição (Cardiovascular)"},
      {"id": "av_gastro", "tipo": "checkbox", "titulo": "2. Gastrointestinal e Digestório", "opcoes": ["Refluxo/azia", "Má digestão", "Gases/flatulência", "Inchaço abdominal", "Diarreia frequente", "Constipação", "Fezes irregulares", "Dor abdominal", "Sensibilidade a alimentos específicos", "Mau hálito", "Outros"]},
      {"id": "av_gastro_freq", "tipo": "number", "titulo": "Frequência de evacuações (número/semana)"},
      {"id": "av_gastro_bristol", "tipo": "text", "titulo": "Consistência (Escala de Bristol)"},
      {"id": "av_hep", "tipo": "checkbox", "titulo": "3. Função Hepática e Biliar", "opcoes": ["Fadiga excessiva", "Dificuldade para digerir gorduras", "Dor no lado direito do abdômen", "Icterícia", "Urina escura", "Fezes claras", "Outros"]},
      {"id": "av_panc", "tipo": "checkbox", "titulo": "4. Função Pancreática e Metabolismo do Açúcar", "opcoes": ["Sede excessiva", "Fome frequente", "Urinar muito", "Sonolência após refeições", "Histórico de diabetes na família", "Outros"]},
      {"id": "av_renal", "tipo": "checkbox", "titulo": "5. Função Renal e Urinária", "opcoes": ["Dor ao urinar", "Urinar frequentemente", "Urina escura/com cheiro forte", "Inchaço facial ou corporal", "Infecções urinárias de repetição", "Outros"]},
      {"id": "av_pulm", "tipo": "checkbox", "titulo": "6. Função Pulmonar e Respiratória", "opcoes": ["Tosse crônica", "Falta de ar", "Chiado no peito", "Asma/Bronquite", "Resfriados frequentes", "Outros"]},
      {"id": "av_nerv", "tipo": "checkbox", "titulo": "7. Sistema Nervoso e Cognitivo", "opcoes": ["Estresse elevado", "Ansiedade", "Depressão", "Irritabilidade", "Mudanças de humor", "Dificuldade de concentração", "Perda de memória", "Dores de cabeça frequentes", "Tontura", "Dormência/formigamento", "Outros"]},
      {"id": "av_oss", "tipo": "checkbox", "titulo": "8. Saúde Óssea e Articular", "opcoes": ["Dores nas articulações", "Rigidez matinal", "Dores musculares", "Fraturas frequentes", "Osteoporose/osteopenia", "Artrose/artrite/reumatismo", "Outros"]},
      {"id": "av_end_tir", "tipo": "checkbox", "titulo": "9A. Sistema Endócrino e Hormonal - Tireoide", "opcoes": ["Cansaço/fadiga", "Ganho de peso", "Dificuldade para perder peso", "Perda de cabelo", "Pele seca", "Intolerância ao frio", "Irregularidade menstrual", "Constipação", "Dificuldade de concentração", "Outros"]},
      {"id": "av_end_mul", "tipo": "checkbox", "titulo": "9B. Sistema Endócrino e Hormonal - Para Mulheres", "opcoes": ["Ciclo menstrual irregular", "TPM intensa", "Menopausa/Climatério", "Problemas ginecológicos", "Alterações nas mamas", "Outros"]},
      {"id": "av_end_mul_espec", "tipo": "text", "titulo": "Especifique os sintomas de Menopausa ou Problemas ginecológicos"},
      {"id": "av_end_hom", "tipo": "checkbox", "titulo": "9C. Sistema Endócrino e Hormonal - Para Homens", "opcoes": ["Baixa libido", "Disfunção erétil", "Alterações na próstata", "Fadiga", "Outros"]},
      {"id": "av_imune", "tipo": "checkbox", "titulo": "10. Sistema Imunológico", "opcoes": ["Resfriados/gripes frequentes", "Infecções de repetição", "Cicatrização lenta", "Herpes de repetição", "Candidíase de repetição", "Outros"]},
      {"id": "sec_5", "tipo": "section", "titulo": "V. ESTILO DE VIDA E HÁBITOS"},
      {"id": "ev_alim_desc", "tipo": "textarea", "titulo": "1. Alimentação - Descrição da alimentação diária"},
      {"id": "ev_alim_ultra", "tipo": "number", "titulo": "Frequência de ultraprocessados (número/semana)"},
      {"id": "ev_alim_acuc", "tipo": "number", "titulo": "Frequência de açúcares (número/semana)"},
      {"id": "ev_alim_farin", "tipo": "number", "titulo": "Frequência de farináceos refinados (número/semana)"},
      {"id": "ev_alim_frit", "tipo": "number", "titulo": "Frequência de frituras (número/semana)"},
      {"id": "ev_alim_carne", "tipo": "number", "titulo": "Frequência de carnes vermelhas (número/semana)"},
      {"id": "ev_alim_peixe", "tipo": "number", "titulo": "Frequência de peixes (número/semana)"},
      {"id": "ev_alim_fruta", "tipo": "number", "titulo": "Porções de frutas (número/dia)"},
      {"id": "ev_alim_veg", "tipo": "number", "titulo": "Porções de vegetais (número/dia)"},
      {"id": "ev_alim_lat", "tipo": "text", "titulo": "Consumo de laticínios (Sim/Não e Frequência)", "placeholder": "Ex: Sim, 2x ao dia"},
      {"id": "ev_alim_glu", "tipo": "text", "titulo": "Consumo de glúten (Sim/Não e Frequência)", "placeholder": "Ex: Sim, 3x na semana"},
      {"id": "ev_alim_rest", "tipo": "textarea", "titulo": "Restrições alimentares"},
      {"id": "ev_hidr_agua", "tipo": "number", "titulo": "2. Hidratação - Consumo de água por dia (litros)"},
      {"id": "ev_hidr_beb", "tipo": "checkbox", "titulo": "Outras bebidas", "opcoes": ["Bebidas açucaradas", "Chá"]},
      {"id": "ev_hidr_cafe", "tipo": "number", "titulo": "Café (xícaras/dia)"},
      {"id": "ev_hidr_outros", "tipo": "textarea", "titulo": "Outras bebidas (especifique)"},
      {"id": "ev_sono_horas", "tipo": "number", "titulo": "3. Sono - Horas de sono por noite"},
      {"id": "ev_sono_prob", "tipo": "checkbox", "titulo": "Problemas de sono", "opcoes": ["Dificuldade para iniciar o sono", "Acorda muitas vezes à noite", "Sono não reparador", "Insônia", "Ronco/Apneia"]},
      {"id": "ev_sono_outros", "tipo": "textarea", "titulo": "Outros problemas de sono"},
      {"id": "ev_estresse_nivel", "tipo": "number", "titulo": "4. Estresse e Saúde Mental - Nível de estresse (0-10)"},
      {"id": "ev_estresse_fontes", "tipo": "checkbox", "titulo": "Fontes de estresse", "opcoes": ["Trabalho", "Família", "Finanças", "Saúde", "Outros"]},
      {"id": "ev_estresse_sintomas", "tipo": "checkbox", "titulo": "Sintomas emocionais", "opcoes": ["Ansiedade", "Tristeza persistente", "Irritabilidade", "Crises de pânico"]},
      {"id": "ev_estresse_hobbies", "tipo": "textarea", "titulo": "Hobbies/atividades relaxantes"},
      {"id": "ev_fis_pratica", "tipo": "radio", "titulo": "5. Atividade Física - Pratica?", "opcoes": ["Sim", "Não"]},
      {"id": "ev_fis_tipo", "tipo": "text", "titulo": "Tipo"},
      {"id": "ev_fis_freq", "tipo": "number", "titulo": "Frequência (número/semana)"},
      {"id": "ev_fis_dur", "tipo": "number", "titulo": "Duração (minutos)"},
      {"id": "ev_tox_fumo", "tipo": "text", "titulo": "6. Exposição a Toxinas - Tabagismo", "placeholder": "Sim/Não/Ex-fumante (tempo)"},
      {"id": "ev_tox_cigarros", "tipo": "number", "titulo": "Cigarros por dia (se sim)"},
      {"id": "ev_tox_alcool", "tipo": "text", "titulo": "Consumo de álcool (Sim/Não + freq/qtd)"},
      {"id": "ev_tox_quimicos", "tipo": "textarea", "titulo": "Exposição a químicos no trabalho/casa"},
      {"id": "ev_tox_poluicao", "tipo": "textarea", "titulo": "Moradia próxima a áreas de poluição"},
      {"id": "ev_tox_cosmeticos", "tipo": "radio", "titulo": "Utiliza cosméticos/produtos com muitos químicos?", "opcoes": ["Sim", "Não"]},
      {"id": "ev_tox_panelas", "tipo": "radio", "titulo": "Utiliza panelas de alumínio?", "opcoes": ["Sim", "Não"]},
      {"id": "sec_6", "tipo": "section", "titulo": "VI. QUEIXAS ESTÉTICAS ESPECÍFICAS"},
      {"id": "qe_pele", "tipo": "checkbox", "titulo": "1. Pele", "opcoes": ["Acne", "Oleosidade excessiva", "Ressecamento", "Manchas", "Flacidez", "Rugas/Linhas de expressão", "Sensibilidade/Vermelhidão", "Rosácea", "Dermatite", "Coceira"]},
      {"id": "qe_pele_acne_loc", "tipo": "text", "titulo": "Localização da Acne"},
      {"id": "qe_pele_tipo", "tipo": "radio", "titulo": "Tipo de pele", "opcoes": ["Seca", "Normal", "Mista", "Oleosa", "Sensível"]},
      {"id": "qe_pele_rotina", "tipo": "textarea", "titulo": "Rotina de cuidados com a pele"},
      {"id": "qe_pele_produtos", "tipo": "textarea", "titulo": "Produtos utilizados"},
      {"id": "qe_cabelo", "tipo": "checkbox", "titulo": "2. Cabelo", "opcoes": ["Queda de cabelo", "Oleosidade excessiva", "Ressecamento/Quebra", "Fios finos/Frágeis", "Caspa/Dermatite no couro cabeludo"]},
      {"id": "qe_cabelo_outros", "tipo": "textarea", "titulo": "Outros (Cabelo)"},
      {"id": "qe_unhas", "tipo": "checkbox", "titulo": "3. Unhas", "opcoes": ["Frágeis/Quebradiças", "Manchas", "Fungos", "Crescimento lento"]},
      {"id": "qe_unhas_outros", "tipo": "textarea", "titulo": "Outros (Unhas)"},
      {"id": "qe_corp", "tipo": "checkbox", "titulo": "4. Corporal", "opcoes": ["Gordura localizada", "Celulite", "Flacidez corporal", "Inchaço"]},
      {"id": "qe_corp_loc", "tipo": "text", "titulo": "Localização (Gordura/Flacidez/Inchaço) e Grau (Celulite)"},
      {"id": "qe_corp_outros", "tipo": "textarea", "titulo": "Outros (Corporal)"},
      {"id": "qe_olhos", "tipo": "checkbox", "titulo": "5. Olhos", "opcoes": ["Olheiras", "Bolsas sob os olhos", "Rugas ao redor dos olhos", "Ressecamento ocular", "Fadiga visual", "Visão embaçada"]},
      {"id": "qe_olhos_outros", "tipo": "textarea", "titulo": "Outros (Olhos)"},
      {"id": "sec_7", "tipo": "section", "titulo": "VII. OBSERVAÇÕES DO PROFISSIONAL"},
      {"id": "obs_prof", "tipo": "textarea", "titulo": "Anotações para o profissional"},
      {"id": "obs_ass_cli", "tipo": "text", "titulo": "Assinatura do Cliente"},
      {"id": "obs_ass_prof", "tipo": "text", "titulo": "Assinatura do Profissional"},
      {"id": "amputados", "tipo": "radio", "titulo": "Tem órgãos amputados? (Biorressonância não identifica órgãos ausentes)", "opcoes": ["Sim", "Não"], "obrigatoria": true}
    ]'::jsonb
WHERE nome_template = 'Padrão Morgana';
